# Generated by Django 4.2.20 on 2025-03-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tuteurAdherent', '0001_initial'),
        ('tuteur', '0001_initial'),
        ('Adherent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutteuradherent',
            name='adherent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherent.adherent'),
        ),
        migrations.AddField(
            model_name='tutteuradherent',
            name='tuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuteur.tuteur'),
        ),
    ]
