# Generated by Django 4.2.20 on 2025-03-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotisation', '0001_initial'),
        ('Adherent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='adherent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='Adherent.adherent'),
        ),
        migrations.AlterUniqueTogether(
            name='cotisation',
            unique_together={('adherent', 'annee')},
        ),
    ]
