# Generated by Django 4.2.20 on 2025-03-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuteur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuteur',
            options={},
        ),
        migrations.AlterModelManagers(
            name='tuteur',
            managers=[
            ],
        ),
    ]
